apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: apiserver
        group: octav
    spec:
      volumes:
        - name: cloudsql
          secret:
            secretName: cloudsql
      containers:
        - image: asia.gcr.io/builderscon-1248/apiserver:8bfc013-debug
          name: apiserver
          env:
            - name: OCTAV_MYSQL_DBNAME
              value: octav
            - name: OCTAV_MYSQL_ADDRESS_FILE
              value: /cloudsql/address
            - name: OCTAV_MYSQL_USERNAME
              value: root
            - name: OCTAV_MYSQL_PASSWORD_FILE
              value: /cloudsql/password
            - name: OCTAV_MYSQL_CA_CERT_FILE
              value: /cloudsql/server-ca.pem
            - name: OCTAV_MYSQL_CLIENT_CERT_FILE
              value: /cloudsql/client-cert.pem
            - name: OCTAV_MYSQL_CLIENT_KEY_FILE
              value: /cloudsql/client-key.pem
            - name: OCTAV_TRACE_DB
              value: "1"
            - name: OCTAV_STORAGE_TYPE
              value: GoogleStorage
            - name: GOOGLE_PROJECT_ID
              value: builderscon-1248
            - name: GOOGLE_LOG_ID
              value: apiserver
            - name: GOOGLE_STORAGE_MEDIA_BUCKET
              value: media-builderscon-1248
            - name: GOOGLE_STORAGE_CREDENTIAL_BUCKET
              value: credentials-builderscon-1248
            - name: MAILGUN_DEFAULT_SENDER
              valueFrom:
                secretKeyRef:
                  name: mailgun
                  key: default.sender
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mailgun
                  key: domain
            - name: MAILGUN_PUBLIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun
                  key: public.api.key
            - name: MAILGUN_SECRET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun
                  key: secret.api.key
            - name: TWITTER_OAUTH2_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: access.token
            - name: TWITTER_OAUTH1_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: consumer.key
            - name: TWITTER_OAUTH1_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: consumer.secret
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: cloudsql
              readOnly: true
              mountPath: /cloudsql