apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: adminweb
        group: octav
    spec:
      volumes:
        # This emptyDir volume is used to populate data from the app container
        # so that the proxy can serve it without asking the app for it
        - name: static-files
          emptyDir:
            medium: Memory
        - name: adminweb
          secret:
            secretName: adminweb
        - name: adminweb-config
          configMap:
            name: adminweb-config
            items:
              - key: config-json
                path: config.json
        - name: googlemaps
          secret:
            secretName: googlemaps
        - name: nginx
          secret:
            secretName: nginx-admin-builderscon-io
        - name: basicauth
          secret:
            secretName: authmap-admin-builderscon-io
      containers:
        - image: asia.gcr.io/builderscon-1248/nginx:20160411.105018
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          name: proxy
          ports:
            - name: ngx-proxy-http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: static-files
              readOnly: true
              mountPath: /static-files
            - name: nginx
              readOnly: true
              mountPath: /etc/nginx
            - name: basicauth
              readOnly: true
              mountPath: /etc/authmap
        - image: asia.gcr.io/builderscon-1248/adminweb:1ce6036-da39a3e-87fd8d6-941fee5
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          lifecycle:
            postStart:
              exec:
                # This command copies the static files to a shared dir so proxy can read it
                command: [ "cp", "-R", "/admin.builderscon.io/static/", "/static-files/" ]
          env:
            - name: ADMINWEB_REDIS_HOST
              value: redis
            - name: ADMINWEB_REDIS_PORT
              value: "6379"
            - name: ADMINWEB_REDIS_DB
              value: "0"
            - name: CONFIG_FILE
              value: /config/config.json
            - name: OCTAV_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: adminweb
                  key: clientkey
            - name: OCTAV_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: adminweb
                  key: clientsecret
            - name: ADMINWEB_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-adminweb
                  key: id
            - name: ADMINWEB_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-adminweb
                  key: secret
            - name: OCTAV_GOOGLE_MAPS_API_KEY
              value: /googlemaps/apikey
            - name: ADMINWEB_FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  name: flask
                  key: secret
            - name: ADMINWEB_FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: facebook
                  key: id
            - name: ADMINWEB_FACEBOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: facebook
                  key: secret
            - name: ADMINWEB_TWITTER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-adminweb
                  key: consumer.key
            - name: ADMINWEB_TWITTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-adminweb
                  key: consumer.secret
            - name: APISERVER_ENDPOINT
              value: http://apiserver-v2:8080
            - name: BASIC_AUTH_MAP
              value: /auth/authmap.pl
            - name: MOJO_MODE
              value: production
          volumeMounts:
            - name: static-files
              mountPath: /static-files
            - name: googlemaps
              readOnly: true
              mountPath: /googlemaps
            - name: adminweb-config
              readOnly: true
              mountPath: /config
            - name: basicauth
              readOnly: true
              mountPath: /auth
