apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: adminweb
        group: octav
    spec:
      volumes:
        # This emptyDir volume is used to populate data from the app container
        # so that the proxy can serve it without asking the app for it
        - name: static-files
          emptyDir:
            medium: Memory
        - name: github
          secret:
            secretName: github
        - name: adminweb
          secret:
            secretName: adminweb
        - name: googlemaps
          secret:
            secretName: googlemaps
        - name: nginx
          secret:
            secretName: nginx-admin-builderscon-io
        - name: basicauth
          secret:
            secretName: authmap-admin-builderscon-io
      containers:
        - image: asia.gcr.io/builderscon-1248/nginx:20160411.105018
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          name: proxy
          ports:
            - name: ngx-proxy-http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: static-files
              readOnly: true
              mountPath: /static-files
            - name: nginx
              readOnly: true
              mountPath: /etc/nginx
        - image: asia.gcr.io/builderscon-1248/adminweb:1de3932-ae38da5-3d0ba35-8f53f28
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          lifecycle:
            postStart:
              exec:
                # This command copies the static files to a shared dir so proxy can read it
                command: [ "cp", "-R", "/adminweb/public/static/", "/static-files/" ]
          env:
            - name: OCTAV_REDIS
              value: redis:6379
            - name: OCTAV_GITHUB_CLIENT_ID
              value: /github/id
            - name: OCTAV_GITHUB_CLIENT_SECRET
              value: /github/secret
            - name: OCTAV_GOOGLE_MAPS_API_KEY
              value: /googlemaps/apikey
            - name: OCTAV_API_CLIENT_KEY
              value: /config/clientkey
            - name: OCTAV_API_CLIENT_SECRET
              value: /config/clientsecret
            - name: OCTAV_TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: consumer.key
            - name: OCTAV_TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter
                  key: consumer.secret
            - name: APISERVER_ENDPOINT
              value: http://apiserver:8080
            - name: BASIC_AUTH_MAP
              value: /auth/authmap.pl
            - name: MOJO_MODE
              value: production
          volumeMounts:
            - name: static-files
              mountPath: /static-files
            - name: github
              readOnly: true
              mountPath: /github
            - name: googlemaps
              readOnly: true
              mountPath: /googlemaps
            - name: adminweb
              readOnly: true
              mountPath: /config
            - name: basicauth
              readOnly: true
              mountPath: /auth
