kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: apiserver-v2
      labels:
        name: apiserver
    spec:
      type: NodePort
      selector:
        name: apiserver-v2
      ports:
        - name: proxy
          port: 8080
          targetPort: 8080
