apiVersion: v1
kind: Service
metadata:
  name: vanity-redirector
  labels:
    name: vanity-redirector
spec:
  type: NodePort
  selector:
    name: vanity-redirector
  ports:
    - port: {{ .Values.Port }}
      targetPort: {{ .Values.Port }}
