apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SecretName }}
  labels:
    name: {{ .Values.SecretName }}
    group: secrets
data:
  authmap: {{ .Files.Get "authmap" | b64enc }}
  googlemap.apikey: {{ .Files.Get "googlemap.txt" | b64enc }}
  client.key: {{ .Files.Get "clientkey.txt" | b64enc }}
  client.secret: {{ .Files.Get "clientsecret.txt" | b64enc }}
