apiVersion: v1
kind: Service
metadata:
    name: confapp
    labels:
        name: confapp
spec:
    type: LoadBalancer
    selector:
        name: confapp
    ports:
        - name: confapp
          port: 8080