apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apiserver
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - api.builderscon.io
    secretName: api-builderscon-io-tls
  rules:
  - host: api.builderscon.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: apiserver
          servicePort: 8080
