apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: builderscon
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - builderscon.io
    - admin.builderscon.io
    secretName: builderscon-io-tls
  rules:
  - host: admin.builderscon.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: adminweb-proxy
          servicePort: 5001
  - host: builderscon.io
    http:
      paths:
      - backend:
          serviceName: confweb-proxy
          servicePort: 5001

