kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: vanity-redirector
      labels:
        name: vanity-redirector
    spec:
      type: NodePort
      selector:
        name: vanity-redirector
      ports:
        - port: 5002
          targetPort: 5002
