apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: confweb
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.ReplicaCount }}
  template:
    metadata:
      labels:
        name: confweb
        group: builderscon
    spec:
      volumes:
        # This emptyDir volume is used to populate data from the app container
        # so that the proxy can serve it without asking the app for it
        - name: static-files
          emptyDir:
            medium: Memory
        # This secret must be created before hand
        - name: nginx
          secret:
            secretName: {{ .Values.Proxy.ConfigName }}
      containers:
        - image: {{ .Values.global.ImageRegistry }}/{{ .Values.global.ProjectID }}/{{ .Values.App.ImageName }}:{{ .Values.App.ContainerTag }}
          name: app
          env:
            - name: CACHE_BACKEND
              value: Redis
            - name: SESSION_BACKEND
              value: Redis
          volumeMounts:
            - name: static-files
              mountPath: /static-files
          lifecycle:
            postStart:
              exec:
                # This command copies the static files to a shared dir so
                # proxy can read it
                command: [ "cp", "-R", "/conf.builderscon.io/static/", "/static-files/" ]
        # proxy that receives traffic. shares the same static file
        # resource set as the app. config file exists in secret
        - image: {{ .Values.global.ImageRegistry }}/{{ .Values.global.ProjectID }}/{{ .Values.Proxy.ImageName }}:{{ .Values.Proxy.ContainerTag }}
          name: proxy 
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits: 
              memory: "128Mi"
              cpu: "200m"
          ports:
            - name: ngx-proxy-http
              containerPort: {{ .Values.Proxy.Port }}
              protocol: TCP
          volumeMounts:
            - name: static-files
              readOnly: true
              mountPath: /static-files
            - name: nginx
              readOnly: true
              mountPath: /etc/nginx